DEF VAR a AS INT NO-UNDO INIT 0.
DEF VAR a AS DEC NO-UNDO INIT 0.
DEF VAR a AS LOG NO-UNDO INIT 0.
DEF VAR a AS CHAR NO-UNDO INIT 0.
DEF VAR a AS LONGCHAR NO-UNDO INIT 0.

DEFINE VARIABLE a AS INTEGER NO-UNDO INITIAL 0.
DEFINE VARIABLE a AS DECIMAL NO-UNDO INITIAL 0.
DEFINE VARIABLE a AS LOGICAL NO-UNDO INITIAL 0.
DEFINE VARIABLE a AS CHARACTER NO-UNDO INITIAL 0.
DEFINE VARIABLE a AS LONGCHAR NO-UNDO INITIAL 0.

PROCEDURE proc:
	DEF INPUT PARAM a AS INT NO-UNDO.
	DEF OUTPUT PARAM b AS INT NO-UNDO.
	DEF INPUT-OUTPUT PARAM b AS INT NO-UNDO.

END PROCEDURE.

RUN proc.

FUNCTION func RETURNS LOGICAL(INPUT a AS INT):
	DEF INPUT PARAM a AS INT NO-UNDO.
END PROCEDURE.

func(2).
